### ISSUE TITLE
F_CPU inaccurately defined

### ISSUE THREAD

**Issue by SpenceKonde** [technoblogy/attiny10core#10]
It looks like boards.txt always sets F_CPU to 8 MHz. But at least according to the datasheet, the chip starts up at 1 MHz and stays there unless the user code tells it to turn off the prescaler? (no hardware to verify this on) - that shouldn't be the case. 

If this is intended, it should be very clearly documented if you have decided to leave it at this on the grounds that most users will be turning off the prescaler, so 8 MHz will be the most common speed and the avrlibc libraries should know that so that _delay_ms() et al will work - but I think better behavior would be to have a menu option to set the clock speed, and have the main.cpp do that before jumping to user code.

**Comment by technoblogy** [comment]
Fixed in 2.0.0.
