### ISSUE TITLE
boards.txt references arduino:standard variant

### ISSUE THREAD

**Issue by SpenceKonde** [technoblogy/attiny10core#11]
```
attiny10.build.variant=arduino:standard
```
This is unnecessary (removing the line does not prevent compilation) and inaccurate:/inappropriate (that variant describes the pin mapping and options used on an uno/nano with '328p processor - though since nothing is including pins_arduino,h this doesn't actually have any impact on the generated code. But with no upside to including it, it's better not to ;-)

**Comment by technoblogy** [comment]
Thanks - fixed in 2.0.0.
