### ISSUE TITLE
Non-functional on Arduino IDE 1.8.9

### ISSUE THREAD

**Issue by goobering** [technoblogy/attiny10core#4]
I'd love to use this. Unfortunately it's not working with a fresh install of Arduino IDE 1.8.9.

Per the instructions, I've put the extracted zip file in a freshly created hardware folder in my Documents\Arduino folder. After that I can see (and have selected) the "ATTiny10/9/5/4" option in my Boards menu, and have selected "USBasp" as my programmer. When I try to build/verify the blink sketch provided [here](http://www.technoblogy.com/show?1YQY) the IDE errors out with `Fatal error: unknown MCU: avrtiny`. I *think* the problem might be related to the AVR-GCC version included with the Arduino IDE, but I'm still trying to test that. Any suggestions very welcome.

**Comment by technoblogy** [comment]
OK, I'll check it myself and let you know.

**Comment by technoblogy** [comment]
Are you running the Arduino IDE on Linux?

**Comment by goobering** [comment]
I'm afraid not - Windows 10 for me. I managed to upgrade the AVR-GCC install and have made a little progress, but I hit outdated firmware on my USBAsp programmer - going to try to get that updated using another Arduino later tonight and I'll see where that takes me.

**Comment by technoblogy** [comment]
That could be the problem - you need the latest firmware. Let me know how you get on.

**Comment by technoblogy** [comment]
These issues should now be solved by the new Boards Manager installation. Thank you for your suggestions.
