### ISSUE TITLE
attiny10/Usbasp problem

### ISSUE THREAD

**Issue by Pricolist** [technoblogy/attiny10core#6]
Usbasp can't work with attiny10
![Снимок](https://user-images.githubusercontent.com/62257070/76781601-07c5b280-67c0-11ea-8c67-1c86f55db4ed.PNG)

**Comment by technoblogy** [comment]
Not sure what the problem might be, but see the discussion on this page:

http://www.technoblogy.com/show?1YQY

**Comment by technoblogy** [comment]
These issues should now be solved by the new Boards Manager installation.
